[package]
name = "selection"
type = "bin"
version = "0.1.0"
edition = "2021"
authors = ["Vices - Subasta Feedlot"]

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }