
bids = [
    { amount = 50000, nonce = 27040, bidder = "0x05f1ac2f722c0af3ce57828e1fcb0ace93ca7610947f595b3828e9c7116980fc", lot_id = 2 },
    { amount = 75000, nonce = 801272, bidder = "0x00dfd4447d21921174aff9647e9ff5a86bcc3dd14aa6349019f43fc854bfcafa", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 },
    { amount = 0, nonce = 0, bidder = "0x0", lot_id = 2 }
]
valid_bids = [true, true, false, false, false, false, false, false]
lot_id = 2
